<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Language;
use Drupal\node\Entity\NodeType;
use Drupal\Core\Link;
use Drupal\Core\Url;
use \Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use \Drupal\views\ViewExecutable;

/*
 * TODO: DOESN'T WORK AT THE MOMENT. Should prevent direct access to the event_date node
 */
function gmfood_general_node_access(EntityInterface $entity, $operation, AccountInterface $account) {
 /* kint($entity);

  \Drupal::logger('gmfood_general_node_access')->notice($entity->getEntityTypeId());
  \Drupal::logger('gmfood_general_node_access')->notice($entity->bundle());

  if ($operation == 'delete') {
    if ($entity->getEntityTypeId() == 'node' && $entity->bundle() == 'event_date') {
      return AccessResult::forbidden();
    }
  }

  return AccessResult::neutral();*/
}


/*
 * uses hook_fullcalendar_classes
 */
function gmfood_general_fullcalendar_classes($entity) {
  //kint($entity->field_calendar);
  //kint($entity->field_calendar[0]);
  //kint($entity->field_calendar[0]->entity);
  $calendar_class = '';
  $calendar_class_id = '';
  $max_length = 32;


  //kint(is_object($entity->field_calendar));

  // check the calendar field is valid
  if(isset($entity->field_calendar) && is_object($entity->field_calendar)) {
    // get transliteration service
    $tr = \Drupal::service('transliteration');
    //kint($entity->field_calendar[0]->entity->getTitle());

    // get the related calendar
    // NOTE: in the case of multiple calendars being referenced, it will pick the first one
    $calendar_title = t($entity->field_calendar[0]->entity->getTitle());

    $calendar_field = $entity->field_calendar[0]->entity->get('field_calendar_serial');
    if (!empty($calendar_field)) {
      $calendar_id = $calendar_field[0]->value;
      $calendar_class_id = 'fc-calendar-' . $calendar_id;
    }
    // kint('serial');
    // kint($calendar_id[0]->value);
    //kint($calendar_id[0]);

    // get default language
    $lang_code = \Drupal::languageManager()->getCurrentLanguage()->getId();

    // remove problematic chars
    $sanitised = $tr->transliterate($calendar_title, $lang_code, $max_length);

    // replace spaces with hypens and lower case string
    $clean_string =  preg_replace('/\-+/', '-', strtolower(preg_replace('/[^a-zA-Z0-9_-]+/', '', str_replace(' ', '-', $sanitised))));
    $calendar_class = 'fc-' . $clean_string;

  }
  // Add the entity type as a class.
  return [
    $entity->entity_type,
    $calendar_class,
    $calendar_class_id
  ];
}

/**
 * Implements hook_entity_extra_field_info().
 */
function gmfood_general_entity_extra_field_info() {
  $extra = array();

  foreach (NodeType::loadMultiple() as $bundle) {
    $extra['node'][$bundle->Id()]['display']['read_more'] = array(
      'label' => t('Read More Link'),
      'description' => t('Displays a read more link to the content'),
      'weight' => 100,
      'visible' => TRUE,
    );
  }

  return $extra;
}

function gmfood_general_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  //kint($entity->getType());
  //kint($build);
  $valid_types = [ 'event' ];
  if (in_array($entity->getType(), $valid_types)) {
    if ($display->getComponent('read_more')) {
        $url = Url::fromRoute('entity.node.canonical', array('node' => $entity->id()));
        $build['read_more_1'] = [
          '#type' => 'link',
          '#url' => $url,
          '#title' => t('Read More'),
          '#weight' => -5,
          '#attributes' => [
            'class' => 'btn btn-primary event__read-more-link'
          ],
        ];
        $build['read_more_2'] = [
          '#type' => 'link',
          '#url' => $url,
          '#title' => t('Read More'),
          '#weight' => 50,
          '#attributes' => [
            'class' => 'btn btn-primary event__read-more-link'
          ],
      ];
    }
  }
}

/*
function gmfood_general_preprocess_views_view_field(&$variables) {
  $view = $variables['view'];
  $field = $variables['field'];
  // kint($view->storage->id() );
  //kint($field->field);
  //kint($view->current_display);
  if ($view->storage->id() == 'single_calendar_view' &&
  $view->current_display == 'single_calendar_view_block' &&
  $field->field == 'view_node') {
    //$variables['output'] = 'https://bbc.co.uk';
    kint($field);
    kint($field);
    kint($field->field);
  }
}
/* NOT WORKING YET
function gmfood_general_preprocess_fullcalendar_event(&$variables) {
  $variables['element'] = [
    '#type'       => 'container',
    '#attributes' => [
      'class' => [
        'fullcalendar-event',
      ],
      'style' => [
        'border-color:red'
      ]
    ],
    'title'       => [
      '#prefix' => '<h3 class="title" style="color:red">',
      '#suffix' => '</h3>',
      '#markup' => $variables['entity']->label(),
    ],
  ];

  foreach ($variables['event'] as $instance) {
    $variables['element'][] = [
      '#type'       => 'container',
      '#attributes' => [
        'class' => [
          'fullcalendar-instance',
        ],
      ],
      [$instance],
    ];
  }
}


function gmfood_general_get_calendar_colour($entity) {

  $calendar_class = '';
  $max_length = 32;

  // check the calendar field is valid
  if(isset($entity->field_calendar) && is_object($entity->field_calendar)) {
    // get transliteration service
    $tr = \Drupal::service('transliteration');
    //kint($entity->field_calendar[0]->entity->getTitle());

    // get the related calendar
    // NOTE: in the case of multiple calendars being referenced, it will pick the first one
    $calendar_title = t($entity->field_calendar[0]->entity->getTitle());

    $calendar_id = t($entity->field_calendar[0]->entity->id());

    // get default language
    $lang_code = \Drupal::languageManager()->getCurrentLanguage()->getId();

    // remove problematic chars
    $sanitised = $tr->transliterate($calendar_title, $lang_code, $max_length);

    // replace spaces with hypens and lower case string
    $clean_string =  preg_replace('/\-+/', '-', strtolower(preg_replace('/[^a-zA-Z0-9_-]+/', '', str_replace(' ', '-', $sanitised))));
    $calendar_class = 'fc-' . $clean_string;
    $calendar_class_id = 'fc-calendar-' . $calendar_id;
    kint($clean_string);
  }
}

*/
